const defaultQuests = [
  // 1–9: Early / Beginner-Friendly
  {
    _id: 1,
    title: 'First Upload',
    description: 'Upload your very first hand history file',
    icon: [ 'fas', 'upload' ],
    reward: 50,
    current: 0,
    target: 1,
    type: 'file-uploads',
    completed: false,
    claimed: false,
  },
  {
    _id: 2,
    title: 'Hand Collector',
    description: 'Upload 200 total hands',
    icon: [ 'fas', 'layer-group' ],
    reward: 75,
    current: 0,
    target: 200,
    type: 'hands',
    completed: false,
    claimed: false,
  },
  {
    _id: 3,
    title: 'Share Knowledge',
    description: 'Share your first session with the community',
    icon: [ 'fas', 'share' ],
    reward: 50,
    current: 0,
    target: 1,
    type: 'posts',
    completed: false,
    claimed: false,
  },
  {
    _id: 4,
    title: 'Analysis Master',
    description: 'Analyze 10 hands using our AI tools',
    icon: [ 'fas', 'brain' ],
    reward: 75,
    current: 0,
    target: 10,
    type: 'analysis',
    completed: false,
    claimed: false,
  },
  {
    _id: 5,
    title: 'Comment Starter',
    description: 'Leave your first comment on another player\'s hand analysis',
    icon: [ 'fas', 'comment-dots' ],
    reward: 50,
    current: 0,
    target: 1,
    type: 'comments',
    completed: false,
    claimed: false,
  },
  {
    _id: 6,
    title: 'Deep Dive',
    description: 'Analyze 50 hands using our AI tools',
    icon: [ 'fas', 'search' ],
    reward: 100,
    current: 0,
    target: 50,
    type: 'analysis',
    completed: false,
    claimed: false,
  },
  {
    _id: 7,
    title: 'Big Uploader',
    description: 'Upload 2,000 total hands',
    icon: [ 'fas', 'cloud-upload-alt' ],
    reward: 125,
    current: 0,
    target: 2000,
    type: 'hands',
    completed: false,
    claimed: false,
  },
  {
    _id: 8,
    title: 'Forum Enthusiast',
    description: 'Create 5 discussion posts in the community',
    icon: [ 'fas', 'comments' ],
    reward: 75,
    current: 0,
    target: 5,
    type: 'posts',
    completed: false,
    claimed: false,
  },
  {
    _id: 9,
    title: 'Constructive Critic',
    description: 'Leave 10 helpful comments on others\' hands',
    icon: [ 'fas', 'thumbs-up' ],
    reward: 75,
    current: 0,
    target: 10,
    type: 'comments',
    completed: false,
    claimed: false,
  },

  // 10–19: Mid-Range / Intermediate
  {
    _id: 10,
    title: 'Hand Historian',
    description: 'Upload 30 separate hand history files (any size)',
    icon: [ 'fas', 'file-upload' ],
    reward: 100,
    current: 0,
    target: 30,
    type: 'file-uploads',
    completed: false,
    claimed: false,
  },
  {
    _id: 11,
    title: 'Session Spotlight',
    description: 'Share 3 of your sessions with the community',
    icon: [ 'fas', 'video' ],
    reward: 75,
    current: 0,
    target: 3,
    type: 'posts',
    completed: false,
    claimed: false,
  },
  {
    _id: 12,
    title: 'Poker Marathon',
    description: 'Upload 15,000 hands in total',
    icon: [ 'fas', 'running' ],
    reward: 200,
    current: 0,
    target: 15000,
    type: 'hands',
    completed: false,
    claimed: false,
  },
  {
    _id: 13,
    title: 'Community Mentor',
    description: 'Post 20 in-depth analyses on others\' hands',
    icon: [ 'fas', 'chalkboard-teacher' ],
    reward: 125,
    current: 0,
    target: 20,
    type: 'comments',
    completed: false,
    claimed: false,
  },
  {
    _id: 14,
    title: 'AI Aficionado',
    description: 'Use the AI analysis tool on 200 different hands',
    icon: [ 'fas', 'robot' ],
    reward: 150,
    current: 0,
    target: 200,
    type: 'analysis',
    completed: false,
    claimed: false,
  },
  {
    _id: 15,
    title: 'Rising Star',
    description: 'Create 15 community posts (sessions, discussions, or guides)',
    icon: [ 'fas', 'star' ],
    reward: 125,
    current: 0,
    target: 15,
    type: 'posts',
    completed: false,
    claimed: false,
  },
  {
    _id: 16,
    title: 'Fearless Filer',
    description: 'Upload 50 hand history files',
    icon: [ 'fas', 'folder-plus' ],
    reward: 150,
    current: 0,
    target: 50,
    type: 'file-uploads',
    completed: false,
    claimed: false,
  },
  {
    _id: 17,
    title: 'Strategist in the Making',
    description: 'Write 5 strategy tips or short guides as community posts',
    icon: [ 'fas', 'lightbulb' ],
    reward: 100,
    current: 0,
    target: 5,
    type: 'posts',
    completed: false,
    claimed: false,
  },
  {
    _id: 18,
    title: 'Thought Leader',
    description: 'Receive 15 upvotes on any of your analyses or comments',
    icon: [ 'fas', 'hands-helping' ],
    reward: 150,
    current: 0,
    target: 15,
    type: 'upvotes',
    completed: false,
    claimed: false,
  },
  {
    _id: 19,
    title: 'AI Connoisseur',
    description: 'Use the AI analysis tool on 400 different hands',
    icon: [ 'fas', 'robot' ],
    reward: 200,
    current: 0,
    target: 400,
    type: 'analysis',
    completed: false,
    claimed: false,
  },

  // 20–27: Advanced / High-Level
  {
    _id: 20,
    title: 'Marathon Poster',
    description: 'Create 30 community posts (any type)',
    icon: [ 'fas', 'align-left' ],
    reward: 200,
    current: 0,
    target: 30,
    type: 'posts',
    completed: false,
    claimed: false,
  },
  {
    _id: 21,
    title: 'Community Champion',
    description: 'Leave 50 helpful comments on others\' hands',
    icon: [ 'fas', 'hands-helping' ],
    reward: 250,
    current: 0,
    target: 50,
    type: 'comments',
    completed: false,
    claimed: false,
  },
  {
    _id: 22,
    title: 'Grand Strategist',
    description: 'Write 10 comprehensive strategy guides as community posts',
    icon: [ 'fas', 'scroll' ],
    reward: 300,
    current: 0,
    target: 10,
    type: 'posts',
    completed: false,
    claimed: false,
  },
  {
    _id: 23,
    title: 'Ultimate Uploader',
    description: 'Upload 50,000 hands in total',
    icon: [ 'fas', 'cloud-upload-alt' ],
    reward: 300,
    current: 0,
    target: 50000,
    type: 'hands',
    completed: false,
    claimed: false,
  },
  {
    _id: 24,
    title: 'Global Mentor',
    description: 'Post 100 in-depth analyses on others\' hands',
    icon: [ 'fas', 'chalkboard-teacher' ],
    reward: 350,
    current: 0,
    target: 100,
    type: 'comments',
    completed: false,
    claimed: false,
  },
  {
    _id: 25,
    title: 'No Stone Unturned',
    description: 'Analyze 1,000 hands using our AI tool',
    icon: [ 'fas', 'brain' ],
    reward: 350,
    current: 0,
    target: 1000,
    type: 'analysis',
    completed: false,
    claimed: false,
  },
  {
    _id: 26,
    title: 'Legendary Poster',
    description: 'Create 100 total community posts (sessions, discussions, or guides)',
    icon: [ 'fas', 'comments' ],
    reward: 400,
    current: 0,
    target: 100,
    type: 'posts',
    completed: false,
    claimed: false,
  },
  {
    _id: 27,
    title: 'Poker Luminary',
    description: 'Receive 100 upvotes on your analyses or comments across the platform',
    icon: [ 'fas', 'trophy' ],
    reward: 500,
    current: 0,
    target: 100,
    type: 'upvotes',
    completed: false,
    claimed: false,
  },

  // 28–33: Extra Final / Ultra-Challenging Quests
  {
    _id: 28,
    title: 'Supreme Archivist',
    description: 'Upload 200 separate hand history files',
    icon: [ 'fas', 'folder-plus' ],
    reward: 400,
    current: 0,
    target: 200,
    type: 'file-uploads',
    completed: false,
    claimed: false,
  },
  {
    _id: 29,
    title: 'Relentless Grinder',
    description: 'Upload 100,000 total hands',
    icon: [ 'fas', 'database' ],
    reward: 400,
    current: 0,
    target: 100000,
    type: 'hands',
    completed: false,
    claimed: false,
  },
  {
    _id: 30,
    title: 'Omniscient Analyst',
    description: 'Use the AI analysis tool on 2,000 different hands',
    icon: [ 'fas', 'robot' ],
    reward: 450,
    current: 0,
    target: 2000,
    type: 'analysis',
    completed: false,
    claimed: false,
  },
  {
    _id: 31,
    title: 'Forum Pioneer',
    description: 'Create 200 total community posts',
    icon: [ 'fas', 'edit' ],
    reward: 500,
    current: 0,
    target: 200,
    type: 'posts',
    completed: false,
    claimed: false,
  },
  {
    _id: 32,
    title: 'Global Advisor',
    description: 'Post 200 in-depth analyses on others\' hands',
    icon: [ 'fas', 'chalkboard-teacher' ],
    reward: 550,
    current: 0,
    target: 200,
    type: 'comments',
    completed: false,
    claimed: false,
  },
  {
    _id: 33,
    title: 'Transcendent Icon',
    description: 'Receive 500 upvotes on your analyses or comments',
    icon: [ 'fas', 'crown' ],
    reward: 600,
    current: 0,
    target: 500,
    type: 'upvotes',
    completed: false,
    claimed: false,
  },
];

module.exports = {
  defaultQuests
};
