/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'solver-node.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./solver-node.android-arm64.node')
          } else {
            nativeBinding = require('solver-node-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'solver-node.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./solver-node.android-arm-eabi.node')
          } else {
            nativeBinding = require('solver-node-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'solver-node.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./solver-node.win32-x64-msvc.node')
          } else {
            nativeBinding = require('solver-node-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'solver-node.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./solver-node.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('solver-node-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'solver-node.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./solver-node.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('solver-node-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'solver-node.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./solver-node.darwin-universal.node')
      } else {
        nativeBinding = require('solver-node-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'solver-node.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./solver-node.darwin-x64.node')
          } else {
            nativeBinding = require('solver-node-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'solver-node.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./solver-node.darwin-arm64.node')
          } else {
            nativeBinding = require('solver-node-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'solver-node.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./solver-node.freebsd-x64.node')
      } else {
        nativeBinding = require('solver-node-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'solver-node.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./solver-node.linux-x64-musl.node')
            } else {
              nativeBinding = require('solver-node-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'solver-node.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./solver-node.linux-x64-gnu.node')
            } else {
              nativeBinding = require('solver-node-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'solver-node.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./solver-node.linux-arm64-musl.node')
            } else {
              nativeBinding = require('solver-node-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'solver-node.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./solver-node.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('solver-node-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'solver-node.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./solver-node.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('solver-node-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'solver-node.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./solver-node.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('solver-node-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'solver-node.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./solver-node.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('solver-node-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'solver-node.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./solver-node.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('solver-node-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'solver-node.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./solver-node.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('solver-node-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { decodeCompactNode, encodeNodeToCompact, decompressZstd, compressZstd, buildFeatureVector, extractBoardTextureJs, batchBuildFeatureVectors, cosineSimilarity, generateActionSequence, leanMetaToFeatureVector, canonicalizeActionHistory, calculateActionHash, formatActionStringJs, generateRangeStats, calculateActionFrequenciesJs, parseActionString, canonicalizeActionTokens, analyzeSnapshot, transformCompactToSolverBlock, calculateRangeAdvantageApi, calculateBlockerImpactApi, analyzeBoardTextureApi, analyzeHandFeatures, analyzeRangeComplete, decodeCompressedNode, unpackAndTransformNode, calculateRangeEquity } = nativeBinding

module.exports.decodeCompactNode = decodeCompactNode
module.exports.encodeNodeToCompact = encodeNodeToCompact
module.exports.decompressZstd = decompressZstd
module.exports.compressZstd = compressZstd
module.exports.buildFeatureVector = buildFeatureVector
module.exports.extractBoardTextureJs = extractBoardTextureJs
module.exports.batchBuildFeatureVectors = batchBuildFeatureVectors
module.exports.cosineSimilarity = cosineSimilarity
module.exports.generateActionSequence = generateActionSequence
module.exports.leanMetaToFeatureVector = leanMetaToFeatureVector
module.exports.canonicalizeActionHistory = canonicalizeActionHistory
module.exports.calculateActionHash = calculateActionHash
module.exports.formatActionStringJs = formatActionStringJs
module.exports.generateRangeStats = generateRangeStats
module.exports.calculateActionFrequenciesJs = calculateActionFrequenciesJs
module.exports.parseActionString = parseActionString
module.exports.canonicalizeActionTokens = canonicalizeActionTokens
module.exports.analyzeSnapshot = analyzeSnapshot
module.exports.transformCompactToSolverBlock = transformCompactToSolverBlock
module.exports.calculateRangeAdvantageApi = calculateRangeAdvantageApi
module.exports.calculateBlockerImpactApi = calculateBlockerImpactApi
module.exports.analyzeBoardTextureApi = analyzeBoardTextureApi
module.exports.analyzeHandFeatures = analyzeHandFeatures
module.exports.analyzeRangeComplete = analyzeRangeComplete
module.exports.decodeCompressedNode = decodeCompressedNode
module.exports.unpackAndTransformNode = unpackAndTransformNode
module.exports.calculateRangeEquity = calculateRangeEquity
